### ISSUE TITLE
Do not crash on Twitter API error

### ISSUE THREAD

**Issue by capital-G** [capital-G/sc-twitter-bot#1]
```docker-compose
bot_1  | Traceback (most recent call last):
bot_1  |   File "/home/sc-twitter-bot/start_bot.py", line 23, in <module>
bot_1  |     twitter_bot.look_for_mentions()
bot_1  |   File "/home/sc-twitter-bot/sc_twitter_bot/sc_twitter_bot.py", line 108, in look_for_mentions
bot_1  |     new_mentions = self.api.mentions_timeline(tweet_mode='extended')
bot_1  |   File "/usr/local/lib/python3.8/site-packages/tweepy/binder.py", line 253, in _call
bot_1  |     return method.execute()
bot_1  |   File "/usr/local/lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
bot_1  |     raise TweepError(error_msg, resp, api_code=api_error_code)
bot_1  | tweepy.error.TweepError: [{'message': 'Over capacity', 'code': 130}]
```

**Comment by capital-G** [comment]
fixed in 896c835
